---
version: '2'
services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    volumes:
      - /opt/plex:/config
      - /mnt/storage:/data
    network_mode: host
    ports:
      - 32400:32400
    restart: always
    environment:
      - PLEX_CLAIM="nope"
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=docker
  
  sabnzbd:
    image: linuxserver/sabnzbd
    container_name: sabnzbd
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - /opt/sabnzbd:/config
      - /mnt/storage/downloads:/downloads
    ports:
      - 27020:8080
      - 27021:9090
    restart: always
  
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    volumes:
      - /opt/sonarr:/config
      - /mnt/storage/tv:/tv
      - /mnt/storage/anime:/anime
      - /mnt/storage/downloads:/downloads
    ports:
      - 27022:8989
    links:
      - sabnzbd
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
  
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    volumes:
      - /opt/radarr:/config
      - /mnt/storage/movies:/movies
      - /mnt/storage/downloads:/downloads
    ports:
      - 27023:7878
    links:
      - sabnzbd
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    restart:
      always
  
  portainer:
    image: portainer/portainer
    container_name: portainer
    ports:
      - 27024:9000
    volumes:
      - /opt/appdata/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart:
      always

  tautulli:
    image: linuxserver/tautulli
    container_name: tautulli
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Indiana/Indianapolis
    volumes:
      - /opt/tautulli:/config
      - /opt/plex/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs
    ports:
      - 8181:8181
    restart: unless-stopped
