---
version: '2'
services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    volumes:
      - /opt/plex:/config
      - /mnt/storage:/data
    network_mode: host
    ports:
      - 32400:32400
    restart: always
    environment:
      - PLEX_CLAIM="nope"
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=docker
  
  sabnzbd:
    image: linuxserver/sabnzbd
    container_name: sabnzbd
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - /opt/sabnzbd:/config
      - /mnt/storage/downloads:/downloads
    ports:
      - 27020:8080
      - 27021:9090
    restart: always
  
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    volumes:
      - /opt/sonarr:/config
      - /mnt/storage/tv:/tv
      - /mnt/storage/anime:/anime
      - /mnt/storage/downloads:/downloads
    ports:
      - 27022:8989
    links:
      - sabnzbd
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
  
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    volumes:
      - /opt/radarr:/config
      - /mnt/storage/movies:/movies
      - /mnt/storage/downloads:/downloads
    ports:
      - 27023:7878
    links:
      - sabnzbd
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    restart:
      always
  
  portainer:
    image: portainer/portainer
    container_name: portainer
    ports:
      - 27024:9000
    volumes:
      - /opt/appdata/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart:
      always

  tautulli:
    image: linuxserver/tautulli
    container_name: tautulli
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Indiana/Indianapolis
    volumes:
      - /opt/tautulli:/config
      - /opt/plex/Library/'Application Support'/'Plex Media Server'/Logs:/logs
    ports:
      - 8181:8181
    restart: unless-stopped
  
  lazylibrarian:
    image: linuxserver/lazylibrarian
    container_name: lazylibrarian
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Indiana/Indianapolis
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    volumes:
      - /opt/lazylibrarian:/config
      - /mnt/storage/downloads:/downloads
      - /mnt/storage/books:/books
    ports:
      - 5299:5299
    restart: unless-stopped

  ombi:
    image: linuxserver/ombi
    container_name: ombi
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Indiana/Indianapolis
    volumes:
      - /opt/ombi/:/config
    ports:
      - 3579:3579
    restart: unless-stopped

  calibre:
    image: linuxserver/calibre
    container_name: calibre
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Indiana/Indianapolis
    volumes:
      - /opt/calibre:/config
    ports:
      - 27025:8080
      - 27026:8081
    restart: unless-stopped

  calibre-web:
    image: linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Indiana/Indianapolis
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    volumes:
      - /opt/calibre_web:/config
      - /opt/calibre/'Calibre Library':/books
    ports:
      - 27027:8083
    restart: unless-stopped

  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Indiana/Indianapolis
    volumes:
      - /opt/heimdall:/config
    ports:
      - 27030:80
      - 27031:443
    restart: unless-stopped